[Definition]
failregex = ^.*"client_ip":"<HOST>".*"uri":"/(?:\.(?:env(?:[./_-][^"]*)?|git(?:/[^"]*)?|aws(?:/[^"]*)?|ssh(?:/[^"]*)?)|manager(?:/[^"]*)?|cgi-bin(?:/[^"]*)?|actuator(?:/[^"]*)?|wp-admin(?:/[^"]*)?|wp-login\.php|xmlrpc\.php|phpmyadmin(?:/[^"]*)?|vendor/phpunit(?:/[^"]*)?)(?:\?[^"]*)?".*"status":404(?:,|}).*$
ignoreregex =
datepattern = "ts":{EPOCH}
