package com.sagongsa.backend.wishlist;

import java.time.Instant;
import java.util.UUID;

record WishlistCursor(Instant createdAt, UUID id) {

	static WishlistCursor parse(String rawCursor) {
		String cursor = rawCursor.trim();
		try {
			int separatorIndex = cursor.lastIndexOf('|');
			if (separatorIndex < 0) {
				return new WishlistCursor(Instant.parse(cursor), null);
			}
			Instant createdAt = Instant.parse(cursor.substring(0, separatorIndex));
			UUID id = UUID.fromString(cursor.substring(separatorIndex + 1));
			return new WishlistCursor(createdAt, id);
		}
		catch (RuntimeException exception) {
			throw new BadRequestException("cursor must be generated by the wishlist list endpoint.");
		}
	}

	static String encode(WishlistItemSummaryResponse item) {
		return item.createdAt() + "|" + item.id();
	}

	boolean hasTieBreaker() {
		return id != null;
	}
}
