package com.sagongsa.backend.wishlist;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.UUID;
import org.junit.jupiter.api.Test;

class WishlistCursorTest {

	private static final UUID ITEM_ID = UUID.fromString("11111111-1111-1111-1111-111111111111");
	private static final UUID USER_ID = UUID.fromString("22222222-2222-2222-2222-222222222222");
	private static final Instant CREATED_AT = Instant.parse("2026-05-25T10:15:30Z");
	private static final Instant UPDATED_AT = Instant.parse("2026-05-25T10:16:30Z");

	@Test
	void encodesCreatedAtAndIdTieBreaker() {
		WishlistItemSummaryResponse item = itemSummary();

		String cursor = WishlistCursor.encode(item);

		assertThat(cursor).isEqualTo("2026-05-25T10:15:30Z|11111111-1111-1111-1111-111111111111");
	}

	@Test
	void parsesEncodedCursorWithTieBreaker() {
		WishlistCursor cursor = WishlistCursor.parse("2026-05-25T10:15:30Z|11111111-1111-1111-1111-111111111111");

		assertThat(cursor.createdAt()).isEqualTo(CREATED_AT);
		assertThat(cursor.id()).isEqualTo(ITEM_ID);
		assertThat(cursor.hasTieBreaker()).isTrue();
	}

	@Test
	void parsesLegacyCreatedAtOnlyCursorWithoutTieBreaker() {
		WishlistCursor cursor = WishlistCursor.parse("2026-05-25T10:15:30Z");

		assertThat(cursor.createdAt()).isEqualTo(CREATED_AT);
		assertThat(cursor.id()).isNull();
		assertThat(cursor.hasTieBreaker()).isFalse();
	}

	@Test
	void trimsRawCursorBeforeParsing() {
		WishlistCursor cursor = WishlistCursor.parse("  2026-05-25T10:15:30Z|11111111-1111-1111-1111-111111111111  ");

		assertThat(cursor.createdAt()).isEqualTo(CREATED_AT);
		assertThat(cursor.id()).isEqualTo(ITEM_ID);
	}

	@Test
	void rejectsMalformedCursor() {
		assertThatThrownBy(() -> WishlistCursor.parse("not-a-cursor"))
			.isInstanceOf(BadRequestException.class)
			.hasMessage("cursor must be generated by the wishlist list endpoint.");
	}

	@Test
	void rejectsCursorWithMissingTieBreakerId() {
		assertThatThrownBy(() -> WishlistCursor.parse("2026-05-25T10:15:30Z|"))
			.isInstanceOf(BadRequestException.class)
			.hasMessage("cursor must be generated by the wishlist list endpoint.");
	}

	private static WishlistItemSummaryResponse itemSummary() {
		return new WishlistItemSummaryResponse(
			ITEM_ID,
			USER_ID,
			"SHARE",
			"https://shop.example/items/1?utm_source=kakao",
			"https://shop.example/items/1",
			"테스트 상품",
			"https://cdn.example/item.jpg",
			15000,
			"KRW",
			"FASHION",
			BigDecimal.valueOf(0.85),
			false,
			"SAVED",
			CREATED_AT,
			UPDATED_AT
		);
	}
}
