spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/404}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  flyway:
    enabled: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${KAKAO_CLIENT_ID:local-kakao-client}
            client-secret: ${KAKAO_CLIENT_SECRET:local-kakao-secret}
management:
  endpoint:
    health:
      show-details: always
