package com.sagongsa.backend.domain.enums;

public enum NotificationType {
	REGRET_CHECK_READY,
	REGRET_CHECK_FOLLOW_UP,
	WISHLIST_REMINDER,
	BUDGET_WARNING,
	BUDGET_RESET,
	SOCIAL_VOTE,
	SOCIAL_FIRST_VOTE,
	SOCIAL_VOTE_SUMMARY,
	SOCIAL_DECISION_NUDGE,
	SOCIAL_COMMENT,
	APP_UPDATE,
	MAINTENANCE_NOTICE
}
